# Generated by Django 4.0.3 on 2022-10-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={'verbose_name': 'BinVO', 'verbose_name_plural': 'BinVOs'},
        ),
    ]
