# Generated by Django 4.0.3 on 2022-10-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={},
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='name',
            new_name='closet_name',
        ),
    ]
